#TMDB.com API key
tmdb: 
  api_key: "7b8bf2fd5c51507ef3e8b77146b67029"
  host: "http://api.themoviedb.org/"
  # host: "http://private-4cb0-themoviedb.apiary.io"
  #host: "http://private-4cb0-themoviedb.apiary-mock.com/"
  base_url: "http://d3gtl9l2a4fn1j.cloudfront.net/t/p/"
  poster:
    size:
      tile: 'w92'
      hero: 'w154'
      pdp: 'w185'
      large: 'w500'

#timeout for services, in seconds
service_call_timeout: 5